/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"main.h"

int main(void)
{
	RCC_AHB1ENR_t volatile *const p_clk_en =(RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODER_t volatile *const p_mode_A =(GPIOx_MODER_t*)0x40020000;
	GPIOx_ODR_t volatile *const p_odr_A =(GPIOx_ODR_t*)0x40020014;
	p_clk_en->GPIOAEN = 1;
	p_mode_A->pin_5 = 0;
	p_mode_A->pin_5 = 1;
	p_odr_A->pin_5 = 1;
	/* Loop forever */
	while(1)
	{
	p_odr_A->pin_5 = 1;
	for(volatile uint32_t i=0;i<500000;i++);
	p_odr_A->pin_5 = 0;
	for(volatile uint32_t i=0;i<500000;i++);

	}
}
