/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
void delay(volatile uint32_t count)
{
	//Time (seconds)=[Clock Frequency (Hz)Iterations×Clock Cycles per Iteration]/Clock Frequency (Hz)
	while(count--);
}
int main(void)
{
    uint32_t volatile *const RCC_AHB1ENR =(uint32_t*) 0x40023830;
    uint32_t volatile *const GPIOB_MODER = (uint32_t*) 0x40020400;
    uint32_t volatile *const GPIOB_ODR = (uint32_t*) 0x40020414;
    uint32_t volatile *const GPIOC_MODER = (uint32_t*) 0x40020800;
    uint32_t volatile *const GPIOC_IDR = (uint32_t*) 0x40020810;
	uint32_t volatile *const GPIOC_PUPDR = (uint32_t*) 0x4002080C;
	//ENABLING CLOCK FOR GPIO B & C
	*RCC_AHB1ENR |= (6<<0);

	//using pins from PB12-PB15 as output R (rows pins):
	//pin 12:
	*GPIOB_MODER &= ~(3<<24);
	*GPIOB_MODER |=  (1<<24);
	//pin 13
	*GPIOB_MODER &= ~(3<<26);
	*GPIOB_MODER |=  (1<<26);
	//pin 14
	*GPIOB_MODER &= ~(3<<28);
	*GPIOB_MODER |=  (1<<28);
	//pin 15
	*GPIOB_MODER &= ~(3<<30);
	*GPIOB_MODER |=  (1<<30);

	//using pins from PC0-PC3 as INput C (COLUMNS pins):
	//pin 0:
	*GPIOC_MODER &= ~(3<<0);
	//pin 1
	*GPIOC_MODER &= ~(3<<2);
	//pin 2
	*GPIOC_MODER &= ~(3<<4);
	//pin 3
	*GPIOC_MODER &= ~(3<<6);

//USING THE PUL UP RESSISTOR FOR OUR INPUT PINS :
	*GPIOC_PUPDR |= (0x55<<0);

/* Loop forever */


	while(1)
	{
		//pulling all THE PB OUTPUT PINS HIGH :
			*GPIOB_ODR |= (0XF<<12);
//pulling  row 1  low (PB12) to test
		*GPIOB_ODR &= ~(1<<12);
delay(500000);
			//testing for which column is high
			//1st colummn PC0
			if(!(*GPIOC_IDR & 0x1))
				printf("button 1 is pressed\n");
			//2nd colummn PC1
			if(!(*GPIOC_IDR & 0x2 ))
				printf("button 2 is pressed\n");
			//3rd colummn PC3
			if(!(*GPIOC_IDR & 0x4 ))
				printf("button 3 is pressed\n");
			//4th colummn PC4
			if(!(*GPIOC_IDR & 0x8 ))
				printf("button 4 is pressed\n");
			//configuring the pin back to high
			*GPIOB_ODR |= (1<<12);

//pulling  row 2  low (PB13) to test
		*GPIOB_ODR &= ~(1<<13);
delay(500000);

			//testing for which column is high
			//1st colummn PC0
			if(!(*GPIOC_IDR & 0x1))
				printf("button 5 is pressed\n");
			//2nd colummn PC1
			if(!(*GPIOC_IDR & 0x2 ))
				printf("button 6 is pressed\n");
			//3rd colummn PC3
			if(!(*GPIOC_IDR & 0x4 ))
			printf("button 7 is pressed\n");
			//4th colummn PC4
			if(!(*GPIOC_IDR & 0x8 ))
			printf("button 8 is pressed\n");
			//configuring tyhe pin back to high
			*GPIOB_ODR |= (1<<13);
//pulling  row 3  low (PB14) to test
			*GPIOB_ODR &= ~(1<<14);
delay(500000);
			//testing for which column is high
			//1st colummn PC0
			if(!(*GPIOC_IDR & 0x1))
			printf("button 9 is pressed\n");
			//2nd colummn PC1
			if(!(*GPIOC_IDR & 0x2 ))
			printf("button A is pressed\n");
			//3rd colummn PC3
			if(!(*GPIOC_IDR & 0x4 ))
			printf("button B is pressed\n");
			//4th colummn PC4
			if(!(*GPIOC_IDR & 0x8 ))
				printf("button C is pressed\n");
			//configuring tyhe pin back to high
						*GPIOB_ODR |= (1<<14);
//pulling  row 4  low (PB15) to test
	*GPIOB_ODR &= ~(1<<15);
delay(500000);
			//testing for which column is high
			//1st colummn PC0
			if(!(*GPIOC_IDR & 0x1))
							printf("button * is pressed\n");
			//2nd colummn PC1
			if(!(*GPIOC_IDR & 0x2 ))
							printf("button 0 is pressed\n");
			//3rd colummn PC3
			if(!(*GPIOC_IDR & 0x4 ))
							printf("button # is pressed\n");
			//4th colummn PC4
			if(!(*GPIOC_IDR & 0x8 ))
							printf("button D is pressed\n");
											}


				return 0;
			}
